/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.company.interfaces.DAOLibros;
import com.mycompany.ilibreria.DAOLibrosImpl;
import com.mycompany.ilibreria.Dashboard;
import com.mycompany.models.LibrosM;
import com.mycompany.models.UsuariosM;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sbeck
 */
public class Libros extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Libros() {
        initComponents();
        InitStyles();
        loadBooks();
    }
    
    private void InitStyles(){
        usuarioB.putClientProperty("FlatLaf.styleClass", "large");
        jButtonBuscarU.putClientProperty("FlatLaf.styleClass", "medium");
        jButtonNuevoU.putClientProperty("FlatLaf.styleClass", "h4");
        jButtonEditarU.putClientProperty("FlatLaf.styleClass", "h4");
        jButtonBorrarU.putClientProperty("FlatLaf.styleClass", "h4");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        usuarioB = new javax.swing.JTextField();
        jButtonBuscarU = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonNuevoU = new javax.swing.JButton();
        jButtonEditarU = new javax.swing.JButton();
        jButtonBorrarU = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 430));

        background.setPreferredSize(new java.awt.Dimension(750, 430));

        usuarioB.setText("Ingrese el usuario a buscar");
        usuarioB.setPreferredSize(new java.awt.Dimension(500, 22));

        jButtonBuscarU.setText("Buscar");
        jButtonBuscarU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscarU.setPreferredSize(new java.awt.Dimension(130, 45));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titulo", "Fecha", "Autor", "Categoria", "Edicion", "Idioma", "Paginas", "Descripcion", "ISBN", "Stock", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonNuevoU.setText("Nuevo");
        jButtonNuevoU.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonNuevoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoUActionPerformed(evt);
            }
        });

        jButtonEditarU.setText("Editar");
        jButtonEditarU.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonEditarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUActionPerformed(evt);
            }
        });

        jButtonBorrarU.setText("Borrar");
        jButtonBorrarU.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonBorrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jButtonNuevoU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBorrarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(usuarioB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(usuarioB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrarU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoUActionPerformed
        Dashboard.ShowJPanel(new UpdateLibros());
    }//GEN-LAST:event_jButtonNuevoUActionPerformed

    private void jButtonEditarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUActionPerformed
        if(jTable1.getSelectedRow() > -1){
            LibrosM libro = new LibrosM();
            libro.setId((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            libro.setTitle(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            libro.setDate(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());            
            libro.setAuthor(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            libro.setCategory(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            libro.setEdit(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            libro.setLang(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            libro.setPages((int)jTable1.getValueAt(jTable1.getSelectedRow(), 7));
            libro.setDescription(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            libro.setISBN(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            libro.setStock((int)jTable1.getValueAt(jTable1.getSelectedRow(), 10));
            libro.setAvailable((int)jTable1.getValueAt(jTable1.getSelectedRow(), 11));
            Dashboard.ShowJPanel(new UpdateLibros(libro));
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario a editar!", "AVISO", 0);
        }
    }//GEN-LAST:event_jButtonEditarUActionPerformed

    private void jButtonBorrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUActionPerformed
        DAOLibros dao = new DAOLibrosImpl();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int i : jTable1.getSelectedRows()){
            try {       
                dao.eliminar((int) jTable1.getValueAt(i, 0));
                model.removeRow(i);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al Eliminar el usuario", "AVISO", 0);
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonBorrarUActionPerformed

    private void loadBooks(){
        try {
            DAOLibros dao = new DAOLibrosImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            dao.listar("").forEach((u) -> model.addRow(new Object[]{u.getId(),u.getTitle(),u.getDate(),u.getAuthor(),u.getCategory(),u.getEdit(),u.getLang(),u.getPages(),u.getDescription(),u.getISBN(),u.getStock(),u.getAvailable()}));
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonBorrarU;
    private javax.swing.JButton jButtonBuscarU;
    private javax.swing.JButton jButtonEditarU;
    private javax.swing.JButton jButtonNuevoU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField usuarioB;
    // End of variables declaration//GEN-END:variables
}
