/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.company.interfaces.DAOLibros;
import com.company.interfaces.DAOPrestamos;
import com.company.interfaces.DAOUsuarios;
import com.mycompany.ilibreria.DAOLibrosImpl;
import com.mycompany.ilibreria.DAOPrestamosImpl;
import com.mycompany.ilibreria.DAOUsuariosImpl;
import com.mycompany.models.LibrosM;
import com.mycompany.models.PrestamosM;
import com.mycompany.models.UsuariosM;
import com.mycompany.utils.utils;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sbeck
 */
public class Prestamos extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Prestamos() {
        initComponents();
        InitStyles();
        initImage();
    }
    
    private void InitStyles(){
        subtitulo.putClientProperty("FlatLaf.styleClass", "h1");
        jLabel1.putClientProperty("FlatLaf.styleClass", "h3");
        jLabel2.putClientProperty("FlatLaf.styleClass", "h3");
        folioU.putClientProperty("FlatLaf.styleClass", "h4");
        libroID.putClientProperty("FlatLaf.styleClass", "h4");
        jButton1.putClientProperty("FlatLaf.styleClass", "h4");
    }
    
    private void initImage(){
        imagen.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Se asegura de que solo se ejecute una vez, cuando las dimensiones sean mayores que 0
                if (imagen.getWidth() > 0 && imagen.getHeight() > 0) {
                    // Carga la imagen 
                    ImageIcon icon = new ImageIcon(getClass().getResource("/Lending.png"));
                    Image resizedImage = icon.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_SMOOTH);
                    imagen.setIcon(new ImageIcon(resizedImage));
    
                    // Remueve el listener una vez que el icono ha sido establecido
                    imagen.removeComponentListener(this);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        background = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        folioU = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        libroID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        subtitulo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(750, 430));

        background.setMinimumSize(new java.awt.Dimension(750, 370));
        background.setPreferredSize(new java.awt.Dimension(750, 370));
        background.setLayout(new java.awt.GridBagLayout());

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagen.setMinimumSize(new java.awt.Dimension(405, 270));
        imagen.setPreferredSize(new java.awt.Dimension(405, 270));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        background.add(imagen, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(15, 110, 86));
        jSeparator1.setForeground(new java.awt.Color(15, 110, 86));
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 110, 86), 2, true));
        jSeparator1.setPreferredSize(new java.awt.Dimension(280, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 0, 30);
        background.add(jSeparator1, gridBagConstraints);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Folio Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 30);
        background.add(jLabel1, gridBagConstraints);

        folioU.setText("Ingrese el folio del usuario");
        folioU.setPreferredSize(new java.awt.Dimension(140, 22));
        folioU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                folioUFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 30);
        background.add(folioU, gridBagConstraints);

        jSeparator2.setBackground(new java.awt.Color(15, 110, 86));
        jSeparator2.setForeground(new java.awt.Color(15, 110, 86));
        jSeparator2.setToolTipText("");
        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 110, 86), 2, true));
        jSeparator2.setPreferredSize(new java.awt.Dimension(280, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 0, 30);
        background.add(jSeparator2, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Libro ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 30);
        background.add(jLabel2, gridBagConstraints);

        libroID.setText("Ingrese el ID del Libro a prestar");
        libroID.setPreferredSize(new java.awt.Dimension(140, 22));
        libroID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                libroIDFocusGained(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 30);
        background.add(libroID, gridBagConstraints);
        libroID.getAccessibleContext().setAccessibleDescription("");

        jButton1.setText("Prestar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(30, 6, 30, 30);
        background.add(jButton1, gridBagConstraints);

        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("Prestamo de Libro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.4;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 30);
        background.add(subtitulo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String folioId = folioU.getText().trim();
        String bookId = libroID.getText().trim();
        
        try {
            if (!utils.validarIds(folioId, bookId)){
            return;
            }
        
            DAOUsuarios daoUsuario = new DAOUsuariosImpl();
            UsuariosM usuarioPrestamo = daoUsuario.obtenerUsuarioPorId(Integer.parseInt(folioId));
            if (usuarioPrestamo.getName() == null){
                JOptionPane.showMessageDialog(this, "No se encontro ningun usuario con ese folio.", "AVISO", 0);
                folioU.requestFocus();
                return;
            }               
            
            DAOLibros daoLibro = new DAOLibrosImpl();
            LibrosM libroPrestamo = daoLibro.obtenerLibroPorId(Integer.parseInt(bookId));
            if (libroPrestamo.getTitle() == null){
                JOptionPane.showMessageDialog(this, "No se encontro ningun libro con ese numero.", "AVISO", 0);
                libroID.requestFocus();
                return;
            }
        
            if (libroPrestamo.getAvailable() < 1){
                JOptionPane.showMessageDialog(this, "No hay mas libros disponibles para prestar.", "AVISO", 0);
                libroID.requestFocus();
                return;
            }
            
            //Validar si el usuario ya tiene un prestamo igual
            PrestamosM prestamoAnt = new PrestamosM();
            DAOPrestamos DAOprestamo = new DAOPrestamosImpl();
            prestamoAnt = DAOprestamo.obtenerPrestamo(usuarioPrestamo.getId(), libroPrestamo.getId());
            if (prestamoAnt != null){
                JOptionPane.showMessageDialog(this, "Esta persona ya cuenta con el prestamo de este libro.", "AVISO", 0);
                libroID.requestFocus();
                return;
            }
        
            PrestamosM prestamoActual = new PrestamosM();
        
            prestamoActual.setBook_id(libroPrestamo.getId());
            prestamoActual.setUser_id(usuarioPrestamo.getId());
            prestamoActual.setDate_out(utils.fechaActual());
        
            DAOprestamo.prestar(prestamoActual);
            libroPrestamo.setAvailable(libroPrestamo.getAvailable() - 1);
            daoLibro.modificar(libroPrestamo);
            DAOprestamo.obtenerPrestamosTotales(libroPrestamo.getId());
            JOptionPane.showMessageDialog(null, "Prestamo Realizado Exitosamente", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error al prestar el libro.", "AVISO", 0);
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void folioUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_folioUFocusGained
        folioU.setText("");
    }//GEN-LAST:event_folioUFocusGained

    private void libroIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_libroIDFocusGained
        libroID.setText("");
    }//GEN-LAST:event_libroIDFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField folioU;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField libroID;
    private javax.swing.JLabel subtitulo;
    // End of variables declaration//GEN-END:variables
}
