/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.company.interfaces.DAOUsuarios;
import com.mycompany.ilibreria.DAOUsuariosImpl;
import static com.mycompany.ilibreria.Dashboard.ShowJPanel;
import com.mycompany.models.UsuariosM;
import javax.swing.JOptionPane;


/**
 *
 * @author sbeck
 */
public class UpdateUsuarios extends javax.swing.JPanel {
    boolean isEdition = false;
    UsuariosM userInfo = new UsuariosM();
    /**
     * Creates new form Principal
     */
    public UpdateUsuarios() {
        initComponents();
        InitStyles();
    }
    
    public UpdateUsuarios(UsuariosM user) {
        initComponents();
        isEdition = true;
        userInfo = user;
        InitStyles();
    }
    
    private void InitStyles(){
        subtitulo.putClientProperty("FlatLaf.styleClass", "h1");
        jLNombre.putClientProperty("FlatLaf.styleClass", "h3");
        jLApellido.putClientProperty("FlatLaf.styleClass", "h3");
        jLDomicilio.putClientProperty("FlatLaf.styleClass", "h3");
        jLTelefono.putClientProperty("FlatLaf.styleClass", "h3");
        jButtonUsuarioUpdate.putClientProperty("FlatLaf.styleClass", "h4");
        if(isEdition){
            subtitulo.setText("Editar Usuario");
            jButtonUsuarioUpdate.setText("Guardar");
            nombreU.setText(userInfo.getName());
            apellidoU.setText(userInfo.getLast_name());
            domicilioU.setText(userInfo.getDomicilio());
            telefonoU.setText(userInfo.getTel());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        subtitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        nombreU = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLApellido = new javax.swing.JLabel();
        apellidoU = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLDomicilio = new javax.swing.JLabel();
        domicilioU = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLTelefono = new javax.swing.JLabel();
        telefonoU = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButtonUsuarioUpdate = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 430));

        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("Registrar nuevo usuario");

        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNombre.setText("Nombre");

        jSeparator1.setBackground(new java.awt.Color(15, 110, 86));
        jSeparator1.setForeground(new java.awt.Color(15, 110, 86));
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 110, 86), 2, true));
        jSeparator1.setPreferredSize(new java.awt.Dimension(280, 2));

        jLApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLApellido.setText("Apellido");

        jSeparator2.setBackground(new java.awt.Color(15, 110, 86));
        jSeparator2.setForeground(new java.awt.Color(15, 110, 86));
        jSeparator2.setToolTipText("");
        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 110, 86), 2, true));
        jSeparator2.setPreferredSize(new java.awt.Dimension(280, 2));

        jLDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDomicilio.setText("Domicilio");

        domicilioU.setPreferredSize(new java.awt.Dimension(280, 22));

        jSeparator3.setBackground(new java.awt.Color(15, 110, 86));
        jSeparator3.setForeground(new java.awt.Color(15, 110, 86));
        jSeparator3.setToolTipText("");
        jSeparator3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 110, 86), 2, true));
        jSeparator3.setPreferredSize(new java.awt.Dimension(260, 2));

        jLTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTelefono.setText("Telefono");

        jSeparator4.setBackground(new java.awt.Color(15, 110, 86));
        jSeparator4.setForeground(new java.awt.Color(15, 110, 86));
        jSeparator4.setToolTipText("");
        jSeparator4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 110, 86), 2, true));
        jSeparator4.setPreferredSize(new java.awt.Dimension(280, 2));

        jButtonUsuarioUpdate.setText("Registrar");
        jButtonUsuarioUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuarioUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jButtonUsuarioUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(177, 177, 177))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreU)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(domicilioU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(telefonoU)
                                    .addComponent(jLTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(apellidoU)
                                    .addComponent(jLApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(97, 97, 97))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(jLNombre)
                        .addGap(18, 18, 18)
                        .addComponent(nombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(jLApellido)
                        .addGap(18, 18, 18)
                        .addComponent(apellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDomicilio)
                    .addComponent(jLTelefono))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(domicilioU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jButtonUsuarioUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        apellidoU.getAccessibleContext().setAccessibleDescription("");
        domicilioU.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsuarioUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioUpdateActionPerformed
        String nombre = nombreU.getText().trim();
        String apellido = apellidoU.getText().trim();
        String domicilio = domicilioU.getText().trim();
        String telefono = telefonoU.getText().trim();
        
        if(nombre.isEmpty() || apellido.isEmpty() || domicilio.isEmpty() || telefono.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos!", "AVISO", 0);
            nombreU.requestFocus();
            return;
        }
        
        UsuariosM user = new UsuariosM();
        user.setId(userInfo.getId());
        user.setName(nombre);
        user.setLast_name(apellido);
        user.setDomicilio(domicilio);
        user.setTel(telefono);
        try {
            DAOUsuarios dao = new DAOUsuariosImpl();
            if(isEdition){
                dao.modificar(user);
            } else {
                dao.registrar(user);
                nombreU.setText("");
                apellidoU.setText("");
                domicilioU.setText("");
                telefonoU.setText("");
            }
            ShowJPanel(new Usuarios());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al registrar el usuario", "AVISO", 0);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonUsuarioUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoU;
    private javax.swing.JPanel background;
    private javax.swing.JTextField domicilioU;
    private javax.swing.JButton jButtonUsuarioUpdate;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLDomicilio;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nombreU;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JTextField telefonoU;
    // End of variables declaration//GEN-END:variables
}
