/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.company.interfaces.DAOLibros;
import com.company.interfaces.DAOPrestamos;
import com.mycompany.ilibreria.DAOLibrosImpl;
import com.mycompany.ilibreria.DAOPrestamosImpl;
import static com.mycompany.ilibreria.Dashboard.ShowJPanel;
import com.mycompany.models.LibrosM;
import javax.swing.JOptionPane;


/**
 *
 * @author sbeck
 */
public class UpdateLibros extends javax.swing.JPanel {
    boolean isEdition = false;
    LibrosM bookInfo = new LibrosM();
    /**
     * Creates new form Principal
     */
    public UpdateLibros() {
        initComponents();
        InitStyles();
    }
    
    public UpdateLibros(LibrosM libro) {
        initComponents();
        bookInfo = libro;
        isEdition = true;
        InitStyles();
    }
    
    private void InitStyles(){
        subtitulo.putClientProperty("FlatLaf.styleClass", "h1");
        jLLibroTitulo.putClientProperty("FlatLaf.styleClass", "default");
        JLLibroEdicion.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroAutor.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroCategoria.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroDescripcion.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroFP.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroISBN.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroIdioma.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroPaginas.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroStock.putClientProperty("FlatLaf.styleClass", "h3");
        jLLibroTitulo.putClientProperty("FlatLaf.styleClass", "h3");
        jButtonUsuarioUpdate.putClientProperty("FlatLaf.styleClass", "h4");
        if(isEdition){
            subtitulo.setText("Editar Libro");
            jButtonUsuarioUpdate.setText("Guardar");
            libroTitulo.setText(bookInfo.getTitle());
            libroIdioma.setText(bookInfo.getLang());
            libroAutor.setText(bookInfo.getAuthor());
            libroPaginas.setText(String.valueOf(bookInfo.getPages()));
            libroDescripcion.setText(bookInfo.getDescription());
            libroCategoria.setText(bookInfo.getCategory());
            libroISBN.setText(bookInfo.getISBN());
            libroFP.setText(bookInfo.getDate());
            libroEdicion.setText(bookInfo.getEdit());
            libroStock.setText(String.valueOf(bookInfo.getStock()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        background = new javax.swing.JPanel();
        subtitulo = new javax.swing.JLabel();
        jLLibroIdioma = new javax.swing.JLabel();
        libroIdioma = new javax.swing.JTextField();
        jLLibroTitulo = new javax.swing.JLabel();
        jLLibroPaginas = new javax.swing.JLabel();
        libroTitulo = new javax.swing.JTextField();
        libroPaginas = new javax.swing.JTextField();
        jLLibroAutor = new javax.swing.JLabel();
        jLLibroDescripcion = new javax.swing.JLabel();
        libroAutor = new javax.swing.JTextField();
        libroDescripcion = new javax.swing.JTextField();
        jLLibroCategoria = new javax.swing.JLabel();
        jLLibroISBN = new javax.swing.JLabel();
        libroCategoria = new javax.swing.JTextField();
        libroISBN = new javax.swing.JTextField();
        jLLibroFP = new javax.swing.JLabel();
        JLLibroEdicion = new javax.swing.JLabel();
        jLLibroStock = new javax.swing.JLabel();
        libroEdicion = new javax.swing.JTextField();
        libroStock = new javax.swing.JTextField();
        jButtonUsuarioUpdate = new javax.swing.JButton();
        libroFP = new com.github.lgooddatepicker.components.DatePicker();

        setPreferredSize(new java.awt.Dimension(750, 430));

        background.setLayout(new java.awt.GridBagLayout());

        subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subtitulo.setText("Registrar nuevo Libro");
        subtitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subtitulo.setIconTextGap(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        background.add(subtitulo, gridBagConstraints);

        jLLibroIdioma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroIdioma.setText("Idioma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        background.add(jLLibroIdioma, gridBagConstraints);

        libroIdioma.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 0, 0);
        background.add(libroIdioma, gridBagConstraints);

        jLLibroTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroTitulo.setText("Titulo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        background.add(jLLibroTitulo, gridBagConstraints);

        jLLibroPaginas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroPaginas.setText("Paginas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        background.add(jLLibroPaginas, gridBagConstraints);

        libroTitulo.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 5);
        background.add(libroTitulo, gridBagConstraints);

        libroPaginas.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 0, 0);
        background.add(libroPaginas, gridBagConstraints);

        jLLibroAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroAutor.setText("Autor");
        jLLibroAutor.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        background.add(jLLibroAutor, gridBagConstraints);

        jLLibroDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroDescripcion.setText("Descripcion");
        jLLibroDescripcion.setAlignmentY(0.0F);
        jLLibroDescripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLLibroDescripcion.setIconTextGap(0);
        jLLibroDescripcion.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 0, 5);
        background.add(jLLibroDescripcion, gridBagConstraints);

        libroAutor.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 5);
        background.add(libroAutor, gridBagConstraints);

        libroDescripcion.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        background.add(libroDescripcion, gridBagConstraints);

        jLLibroCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroCategoria.setText("Categoria");
        jLLibroCategoria.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        background.add(jLLibroCategoria, gridBagConstraints);

        jLLibroISBN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroISBN.setText("ISBN");
        jLLibroISBN.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        background.add(jLLibroISBN, gridBagConstraints);

        libroCategoria.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 5);
        background.add(libroCategoria, gridBagConstraints);

        libroISBN.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 0, 0);
        background.add(libroISBN, gridBagConstraints);

        jLLibroFP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroFP.setText("Fecha de Publicacion");
        jLLibroFP.setPreferredSize(new java.awt.Dimension(155, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        background.add(jLLibroFP, gridBagConstraints);

        JLLibroEdicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLLibroEdicion.setText("Edicion");
        JLLibroEdicion.setPreferredSize(new java.awt.Dimension(155, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        background.add(JLLibroEdicion, gridBagConstraints);

        jLLibroStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLLibroStock.setText("Stock");
        jLLibroStock.setPreferredSize(new java.awt.Dimension(155, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        background.add(jLLibroStock, gridBagConstraints);

        libroEdicion.setMinimumSize(new java.awt.Dimension(150, 22));
        libroEdicion.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 5);
        background.add(libroEdicion, gridBagConstraints);

        libroStock.setMinimumSize(new java.awt.Dimension(150, 22));
        libroStock.setPreferredSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 0, 0);
        background.add(libroStock, gridBagConstraints);

        jButtonUsuarioUpdate.setText("Registrar");
        jButtonUsuarioUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuarioUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUsuarioUpdate.setMinimumSize(new java.awt.Dimension(300, 23));
        jButtonUsuarioUpdate.setPreferredSize(new java.awt.Dimension(300, 40));
        jButtonUsuarioUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 20, 5);
        background.add(jButtonUsuarioUpdate, gridBagConstraints);

        libroFP.setMinimumSize(new java.awt.Dimension(200, 21));
        libroFP.setPreferredSize(new java.awt.Dimension(200, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 0.25;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        background.add(libroFP, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUsuarioUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioUpdateActionPerformed
        String titulo = libroTitulo.getText().trim();
        String idioma = libroIdioma.getText().trim();
        String autor = libroAutor.getText().trim();
        String paginas = libroPaginas.getText().trim();
        String descripcion =  libroDescripcion.getText().trim();
        String categoria =  libroCategoria.getText().trim();
        String ISBN =  libroISBN.getText().trim();
        String fechaP =  libroFP.getText().trim();
        String edicion =  libroEdicion.getText().trim();
        String stock =  libroStock.getText().trim();
        
        if(titulo.isEmpty() || idioma.isEmpty() || autor.isEmpty() || paginas.isEmpty() || descripcion.isEmpty() || categoria.isEmpty() || ISBN.isEmpty() || fechaP.isEmpty() || edicion.isEmpty()|| stock.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos!", "AVISO", 0);
            libroTitulo.requestFocus();
            return;
        }
        
        if(Integer.parseInt(paginas) <= 0){
            JOptionPane.showMessageDialog(null, "Paginas tiene que ser mayor a 0!", "AVISO", 0);
            libroPaginas.requestFocus();
            return;
        }
        
        LibrosM book = new LibrosM();
        book.setId(bookInfo.getId());
        book.setTitle(titulo);
        book.setLang(idioma);
        book.setAuthor(autor);
        book.setPages(Integer.parseInt(paginas));
        book.setDescription(descripcion);
        book.setCategory(categoria);
        book.setISBN(ISBN);
        book.setDate(fechaP);
        book.setEdit(edicion);
        book.setStock(Integer.parseInt(stock));
        DAOPrestamos daoPrestamos = new DAOPrestamosImpl();
        int disponibles = book.getStock() - daoPrestamos.obtenerPrestamosTotales(book.getId());
        if (disponibles < 0){
            JOptionPane.showMessageDialog(null, "Stock menor a la cantidad de libros prestados! \n Por favor ingresar numero igual o mayor a " + daoPrestamos.obtenerPrestamosTotales(book.getId()), "AVISO", 0);
            return;
            }
        book.setAvailable(disponibles);
        try {
            DAOLibros dao = new DAOLibrosImpl();
            if(isEdition){
                dao.modificar(book);
            } else {
                dao.registrar(book);
            }
            ShowJPanel(new Libros());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al registrar el libro", "AVISO", 0);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonUsuarioUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLLibroEdicion;
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonUsuarioUpdate;
    private javax.swing.JLabel jLLibroAutor;
    private javax.swing.JLabel jLLibroCategoria;
    private javax.swing.JLabel jLLibroDescripcion;
    private javax.swing.JLabel jLLibroFP;
    private javax.swing.JLabel jLLibroISBN;
    private javax.swing.JLabel jLLibroIdioma;
    private javax.swing.JLabel jLLibroPaginas;
    private javax.swing.JLabel jLLibroStock;
    private javax.swing.JLabel jLLibroTitulo;
    private javax.swing.JTextField libroAutor;
    private javax.swing.JTextField libroCategoria;
    private javax.swing.JTextField libroDescripcion;
    private javax.swing.JTextField libroEdicion;
    private com.github.lgooddatepicker.components.DatePicker libroFP;
    private javax.swing.JTextField libroISBN;
    private javax.swing.JTextField libroIdioma;
    private javax.swing.JTextField libroPaginas;
    private javax.swing.JTextField libroStock;
    private javax.swing.JTextField libroTitulo;
    private javax.swing.JLabel subtitulo;
    // End of variables declaration//GEN-END:variables
}
