/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import com.company.interfaces.DAOUsuarios;
import com.mycompany.ilibreria.DAOUsuariosImpl;
import com.mycompany.ilibreria.Dashboard;
import com.mycompany.models.UsuariosM;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sbeck
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Usuarios() {
        initComponents();
        InitStyles();
        loadUsers();
    }
    
    private void InitStyles(){
        usuarioB.putClientProperty("FlatLaf.styleClass", "h3");
        jButtonBuscarU.putClientProperty("FlatLaf.styleClass", "h4");
        jButtonNuevoU.putClientProperty("FlatLaf.styleClass", "h4");
        jButtonEditarU.putClientProperty("FlatLaf.styleClass", "h4");
        jButtonBorrarU.putClientProperty("FlatLaf.styleClass", "h4");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        usuarioB = new javax.swing.JTextField();
        jButtonBuscarU = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonNuevoU = new javax.swing.JButton();
        jButtonEditarU = new javax.swing.JButton();
        jButtonBorrarU = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 430));

        background.setPreferredSize(new java.awt.Dimension(750, 430));

        usuarioB.setText("Ingrese el nombre del usuario a buscar");
        usuarioB.setPreferredSize(new java.awt.Dimension(570, 40));

        jButtonBuscarU.setText("Buscar");
        jButtonBuscarU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscarU.setPreferredSize(new java.awt.Dimension(130, 40));
        jButtonBuscarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarUActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Domicilio", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        jButtonNuevoU.setText("Nuevo");
        jButtonNuevoU.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonNuevoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoUActionPerformed(evt);
            }
        });

        jButtonEditarU.setText("Editar");
        jButtonEditarU.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonEditarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUActionPerformed(evt);
            }
        });

        jButtonBorrarU.setText("Borrar");
        jButtonBorrarU.setPreferredSize(new java.awt.Dimension(95, 25));
        jButtonBorrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(jButtonNuevoU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBorrarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(usuarioB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)
                        .addComponent(jButtonBuscarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevoU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrarU, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoUActionPerformed
        Dashboard.ShowJPanel(new UpdateUsuarios());
    }//GEN-LAST:event_jButtonNuevoUActionPerformed

    private void jButtonBorrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarUActionPerformed
        DAOUsuarios dao = new DAOUsuariosImpl();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int i : jTable1.getSelectedRows()){
            try {       
                dao.eliminar((int) jTable1.getValueAt(i, 0));
                model.removeRow(i);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocurrio un error al Eliminar el usuario", "AVISO", 0);
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonBorrarUActionPerformed

    private void jButtonEditarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUActionPerformed
        if(jTable1.getSelectedRow() > -1){
            UsuariosM user = new UsuariosM();
            user.setId((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            user.setName(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            user.setLast_name(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            user.setDomicilio(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            user.setTel(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            Dashboard.ShowJPanel(new UpdateUsuarios(user));
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario a editar!", "AVISO", 0);
        }
    }//GEN-LAST:event_jButtonEditarUActionPerformed

    private void jButtonBuscarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarUActionPerformed
        try {
            DAOUsuarios dao = new DAOUsuariosImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            dao.listar(usuarioB.getText()).forEach((u) -> model.addRow(new Object[]{u.getId(),u.getName(),u.getLast_name(),u.getDomicilio(),u.getTel()}));
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonBuscarUActionPerformed
    
    private void loadUsers(){
        try {
            DAOUsuarios dao = new DAOUsuariosImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            dao.listar("").forEach((u) -> model.addRow(new Object[]{u.getId(),u.getName(),u.getLast_name(),u.getDomicilio(),u.getTel()}));
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jButtonBorrarU;
    private javax.swing.JButton jButtonBuscarU;
    private javax.swing.JButton jButtonEditarU;
    private javax.swing.JButton jButtonNuevoU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField usuarioB;
    // End of variables declaration//GEN-END:variables
}
